language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
install:
    - go get github.com/munsy/raideriogo
    - go get -v .
    - go gete -v github.com/golang/lint/golint
  script:
    - diff <(gofmt -d .) <(echo -n)
    - go vet -x ./...
    - golint -set_exit_status ./...
    - go test -v -race ./...