language: go
go:
- 1.7.x
- 1.8.x
- 1.9.x
- 1.10.x
install:
- go get github.com/munsy/raideriogo
- go get -v .
- go get -v github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- diff <(gofmt -d .) <(echo -n)
- go vet -x ./...
- golint -set_exit_status ./...
- go test -v -race ./...
- go test -v -covermode=count -coverprofile=coverage.out
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
env:
  global:
  - secure: 1tktIFg7PQj6kirX6aF8Zo5FErAhwhBWuDeqT1mtmamW+qEMCm4jB6ADiWKrOHCwpXM/kZqAPFbWk8mk8YVd5Ew8QppuEX+LWzIENhO+/j+E1E2jY1msnUAF8RpQCh+LsVKlfk+qvFlhPa58BRjHeDo1ZIFo5W0u0jEQq1N18/+joZqG90hnngEOlOmbO9vRBBXCCOIHgXwveA64n1qcdODr+PHb2mCb1Q8jO739ylGminuKAOYzmARhxYDEq4pbVAxX2CvbhmLmvyi68YKou9S2uTBDcXKozna0egFBEPa+ZRbxpqO0i60IJydG/WM5gt7JsIzoz/tXFUMUg3FfsY7dk+KszOu5H7roNjffUlOchjzaFAGj4FuHennVxmCphxMK2EHoNcGQbICcgdHsmV+Tx7GD3tT1kFWiinLR+LXxc6CHJXNx1wyWD7f0okXh754FiDq5jO+P4wm+COl6K8/QrXIMQ2NQt/pVm/H1uClhqIOfCNRwUySxjVlusj4vk2HTUxfW3QScxxrFf9+PzqLFirKRJLUhrXOZA/k6NKsjyGknXagBsHuBDJC8EafiLp9x4BUG4PTEEqZPdNlJE9xMQNqXEga4WBfY+sge27Vd37sEEA+8nDmC1EwgBnt0bd31VrPKBtK4xleFmkQRNC7hvxZivGTFOI3yZimQ7I0=
