os:
  - linux
language: go
go:
  - 1.10.x
install:
  - go get github.com/munsy/raideriogo
  - go get github.com/go-test/deep
  - go get -v .
  - go get -v github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint -set_exit_status ./...
  - go test -v -race ./...
